### ISSUE TITLE
graph is not getting generated

### ISSUE THREAD

**Issue by arunchannaraju18** [axt/angr-utils#30]
Traceback (most recent call last):
  File "/home/a/.virtualenvs/angr/lib/python3.6/site-packages/pydot.py", line 1926, in create
    working_dir=tmp_dir,
  File "/home/a/.virtualenvs/angr/lib/python3.6/site-packages/pydot.py", line 139, in call_graphviz
    **kwargs
  File "/usr/lib/python3.6/subprocess.py", line 729, in __init__
    restore_signals, start_new_session)
  File "/usr/lib/python3.6/subprocess.py", line 1364, in _execute_child
    raise child_exception_type(errno_num, err_msg, err_filename)
FileNotFoundError: [Errno 2] No such file or directory: 'dot': 'dot'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "cfg123.py", line 7, in <module>
    plot_cfg(cfg, "ais3_cfg", asminst=True, remove_imports=True, remove_path_terminator=True)  
  File "/home/a/ang-dev/angr-utils/angrutils/visualize.py", line 34, in plot_cfg
    vis.process(cfg.graph) 
  File "/home/a/ang-dev/bingraphvis/bingraphvis/base.py", line 310, in process
    return self.output.generate(graph)
  File "/home/a/ang-dev/bingraphvis/bingraphvis/output.py", line 217, in generate
    dotfile.write("{}.{}".format(self.fname, self.format), format=self.format)
  File "/home/a/.virtualenvs/angr/lib/python3.6/site-packages/pydot.py", line 1828, in write
    s = self.create(prog, format, encoding=encoding)
  File "/home/a/.virtualenvs/angr/lib/python3.6/site-packages/pydot.py", line 1933, in create
    raise OSError(*args)
FileNotFoundError: [Errno 2] "dot" not found in path.

How can i solve this problem

**Comment by axt** [comment]
See in this thread:
https://github.com/axt/angr-utils/issues/17#issuecomment-385303946
